# Generated by Django 5.0.6 on 2024-07-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=50)),
                ('roomNumber', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAvailable', models.BooleanField(default=True)),
                ('bedType', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.roomdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('patientMobile', models.CharField(max_length=15)),
                ('checkinDate', models.DateField()),
                ('checkoutDate', models.DateField(blank=True, null=True)),
                ('patientAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('patientEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=15, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('currentDiagnosis', models.TextField(blank=True, null=True)),
                ('doctorAssigned', models.CharField(blank=True, max_length=100, null=True)),
                ('bed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.beddetails')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.roomdetails')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.warddetails')),
            ],
        ),
    ]
