# Generated by Django 5.0.6 on 2024-07-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='checkinDate',
            new_name='checkInDate',
        ),
        migrations.RenameField(
            model_name='warddetails',
            old_name='wardtype',
            new_name='wardType',
        ),
        migrations.RemoveField(
            model_name='beddetails',
            name='bedType',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='checkoutDate',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='beddetails',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.warddetails'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='admitTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='dischargeTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='checkOutDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
